### PR TITLE
update to v0.4.0

### PR DESCRIPTION
**Pull request by tvdboom**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tvdboom** [comment]
@conda-forge-admin, please rerender

**Comment by oegedijk** [comment]
Hi @tvdboom, thanks for taking this up. Seems build tests are still failing during setup. I've restarted it, let's see if if it was just a random failure.

**Comment by oegedijk** [comment]
so seems it cannot find `requirements.txt`?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=543364&view=logs&jobId=516f237f-98f1-50a4-0946-c43fe5437b81&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=68e286c4-c87b-5a2e-10c4-f21f8bc51a62

**Comment by tvdboom** [comment]
yes, it looks like `requirements.txt` is not passed along with the files in the build. You may need a `MANIFEST.in` file (see https://github.com/tvdboom/ATOM/blob/master/MANIFEST.in). I am not 100% sure this will fix it though. And you'll need to release a new pip version to test if it works.

**Pull request merged**
