### PR TITLE
rm slicer

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I think we had to pin slicer as it wasn't in the shap feedstock. Now it is I think it can be removed.
https://github.com/conda-forge/shap-feedstock/blob/master/recipe/meta.yaml#L36

### CODE REVIEW

**Comment by raybellwaves** [comment]
@conda-forge-admin, please rerender

**Comment by raybellwaves** [comment]
I'll also look at removing shortuuid (https://github.com/oegedijk/explainerdashboard/commit/9ab7b8cfb63d76debdd9daa3929a4f5574b26b1d)

**Comment by raybellwaves** [comment]
@oegedijk hope you're ok with me merging. Should stop me raising issues like https://github.com/oegedijk/explainerdashboard/issues/137. Thanks for your ongoing work.

**Comment by oegedijk** [comment]
okay, sounds good! go ahead!

**Pull request merged**
