### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by raybellwaves**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by raybellwaves** [comment]
diving into the slicer issue a bit more

Shap says requires slicer==0.0.7 https://github.com/slundberg/shap/blob/b031fc5da5b08dc08b83a4d890ababd83ed7b5a6/setup.py#L221

Slicer feedstock is at 0.0.7 https://github.com/conda-forge/slicer-feedstock/blob/master/recipe/meta.yaml#L2

Shap has slicer in it's feedstock https://github.com/conda-forge/shap-feedstock/blob/master/recipe/meta.yaml#L37

**Comment by raybellwaves** [comment]
I'll add flask_simplelogin to conda-forge

`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'flask_simplelogin'}
`

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=259407&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=489

**Comment by raybellwaves** [comment]
working on `flask_simplelogin` here

https://github.com/conda-forge/staged-recipes/pull/13630

**Comment by raybellwaves** [comment]
@conda-forge-admin, please restart ci

**Comment by raybellwaves** [comment]
@conda-forge-admin, please restart ci

**Comment by raybellwaves** [comment]
Still saying `conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'flask_simplelogin'}`

It's there (https://github.com/conda-forge/flask_simplelogin-feedstock) but may take time until it appears in the CI

**Comment by oegedijk** [comment]
@conda-forge-admin, please restart ci

**Review by oegedijk — COMMENTED** [review]
seems fine!

**Comment by oegedijk** [comment]
@raybellwaves is there anything I should be doing here? Sorry, not so experienced with conda-forge build...

**Comment by raybellwaves** [comment]
Believe this was an old one

**Pull request closed without merging**
